[build]
  functions = "netlify/functions"

[functions."anime-mapping-updater"]
  schedule = "@daily"

[[redirects]]
  from = "/api/anime-mapping"
  to = "/.netlify/functions/anime-mapping"
  status = 200
